DATASET:
  CNS:
    CNS_ROOT_DIR : ""
    FILE_NAME:
      cnse :  ""
      cnss : ""
    PERIOD_CHAR : '。'
  WORD:
    CSV_PATH     : ""
    RAW_DATA_DIR : ""
    WIKI_DOC_DIR : ""
    META_DATA_NAME : ""
    PERIOD_CHAR : '.'
  MAX_SEG_LEN : 256
  MAX_SEG_NUM : 1
  MAX_PART_NUM : 1
  # MODE : concatenation
  SCORE_THRESHOLD : 0.0

MODEL:
  POOLER_TYPE : 'cls'
  CNS:
    bert :    'hfl/chinese-bert-wwm'
    roberta : 'hfl/chinese-roberta-wwm-ext'
    xlnet :   'hfl/chinese-xlnet-base'
  WORD:
    bert :    'bert-base-uncased'
    roberta : 'roberta-base'
    xlnet :   'xlnet-base-cased'
  HISTORY_NAME : 'history.json'
